package com.tempo.tempoapp.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing an infusion event in the database.
 *
 * @property id The unique identifier of the infusion event, auto-generated by the database.
 * @property treatment The name of the treatment administered.
 * @property infusionSite The site where the infusion was administered.
 * @property doseUnits The dose of the treatment in units.
 * @property lotNumber The lot number of the treatment.
 * @property note Any additional notes regarding the infusion event.
 * @property timestamp The timestamp of when the infusion event was recorded in milliseconds.
 * @property date The date of the infusion event in milliseconds.
 * @property isSent Boolean indicating if the event data has been sent to the server.
 */
@Entity(tableName = "infusion_event")
data class InfusionEvent(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    @ColumnInfo(name = "treatment")
    val treatment: String,
    @ColumnInfo(name = "infusion_site")
    val infusionSite: String,
    @ColumnInfo(name = "dose_in_units")
    val doseUnits: Int,
    @ColumnInfo(name = "lot_number")
    val lotNumber: Int,
    @ColumnInfo(name = "note")
    val note: String?,
    @ColumnInfo(name = "timestamp")
    val timestamp: Long,
    @ColumnInfo(name = "date")
    val date: Long,
    @ColumnInfo(name = "is_sent")
    val isSent: Boolean = false
)



/**
 * Data class representing the JSON structure of an infusion event.
 *
 * @property id The unique identifier of the infusion event.
 * @property treatment The name of the treatment administered.
 * @property infusion_site The site where the infusion was administered.
 * @property dose_in_units The dose of the treatment in units.
 * @property lot_number The lot number of the treatment.
 * @property note Any additional notes regarding the infusion event.
 * @property timestamp The timestamp of when the infusion event was recorded in milliseconds.
 * @property date The date of the infusion event in milliseconds.
 */
data class InfusionEventJson(
    val id: Int = 0,
    val treatment: String,
    val infusion_site: String,
    val dose_in_units: Int,
    val lot_number: Int,
    val note: String?,
    val timestamp: Long,
    val date: Long,
)


/**
 * Extension function to convert an [InfusionEvent] object to an [InfusionEventJson] object.
 *
 * @param id The unique identifier of the infusion event, default is 0.
 * @return The [InfusionEventJson] representation of the infusion event.
 */
fun InfusionEvent.toInfusionEventJson(id: Int = 0): InfusionEventJson =
    InfusionEventJson(id, treatment, infusionSite, doseUnits, lotNumber, note, timestamp, date)