package com.tempo.tempoapp.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * A set of predefined events for reminders.
 */
val events = setOf(
    "Infusione",
    "Visita di controllo",
    "Refill farmaco"
)

/**
 * Entity class representing a reminder event in the database.
 *
 * @property id The unique identifier of the reminder event, auto-generated by the database.
 * @property idCalendar The calendar ID associated with the reminder event.
 * @property event The type of event being reminded, chosen from the predefined [events] set.
 * @property timestamp The timestamp of when the reminder event is scheduled in milliseconds.
 * @property isPeriodic Boolean indicating if the reminder is periodic.
 * @property period The period of the reminder if it is periodic, in the unit specified by [timeUnit].
 * @property timeUnit The unit of time for the period, e.g., "days", "weeks", "months".
 */
@Entity(tableName = "reminder")
data class ReminderEvent(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    @ColumnInfo("id_calendar")
    val idCalendar: Long,
    @ColumnInfo("event")
    val event: String,
    @ColumnInfo("timestamp")
    val timestamp: Long,
    @ColumnInfo("is_periodic")
    val isPeriodic: Boolean,
    @ColumnInfo("period")
    val period: Long,
    @ColumnInfo("time_unit")
    val timeUnit: String
) : Serializable
