package com.tempo.tempoapp.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.Instant
import java.time.temporal.ChronoUnit

/**
 * Entity class representing a record of steps taken in the database.
 *
 * @property id The unique identifier of the steps record, auto-generated by the database.
 * @property steps The number of steps taken.
 * @property date The date of the record in milliseconds.
 * @property startTime The start time of the recorded steps in milliseconds.
 * @property endTime The end time of the recorded steps in milliseconds.
 * @property isSent Boolean indicating if the steps record has been sent to the server.
 */

typealias StepsRecordModel = StepsRecord

@Entity(tableName = "steps", indices = [Index(value = ["record_id"], unique = true)])
data class StepsRecord(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    @ColumnInfo(name = "record_id")
    val recordId: String,
    @ColumnInfo(name = "steps")
    val steps: Long,
    @ColumnInfo(name = "date")
    val date: Long,
    @ColumnInfo(name = "startTime")
    val startTime: Long,
    @ColumnInfo(name = "endTime")
    val endTime: Long,
    @ColumnInfo(name = "is_sent")
    val isSent: Boolean = false
)

/**
 * Extension function to convert an [Instant] to a timestamp in milliseconds, truncated to the specified [ChronoUnit].
 *
 * @param unit The [ChronoUnit] to truncate the instant to.
 * @return The timestamp in milliseconds.
 */
fun Instant.toTimestamp(unit: ChronoUnit) = this.truncatedTo(unit).toEpochMilli()